# Generated by Django 3.0.5 on 2022-03-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220222_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='margin_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spot_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
