# Generated by Django 3.0.5 on 2022-04-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220310_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='decode_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
