# Generated by Django 3.0.5 on 2022-04-26 15:48

from django.db import migrations

from core.utils import hash
from users.models import User


def update_decode_key_keys_and_secret_keys(*args, **kwargs):
    for user in User.objects.all():
        user.decode_key = hash.generate_key()
        user.secret_key = hash.decode(user.decode_key, user.secret_key)
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_user_decode_key'),
    ]

    operations = [
        migrations.RunPython(update_decode_key_keys_and_secret_keys)
    ]
