# Generated by Django 3.0.5 on 2022-03-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('trade_type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], max_length=255)),
                ('loop', models.BooleanField(default=False)),
                ('time_interval', models.IntegerField(default=60)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'main_trades',
                'abstract': False,
            },
        ),
    ]
