# Generated by Django 3.0.5 on 2022-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_trade_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='filled',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
