# Generated by Django 3.0.5 on 2022-03-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220322_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='take_profit_percent',
            field=models.FloatField(default=0),
        ),
    ]
