# Generated by Django 3.0.5 on 2022-03-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_trade_take_profit_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='iceberg_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
