# Generated by Django 3.0.5 on 2022-04-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_trade_iceberg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='completed_loops',
            field=models.IntegerField(default=0),
        ),
    ]
