# Generated by Django 3.0.5 on 2022-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_trade_completed_loops'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='grid_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='grid_end_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='grid_start_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='grid_trades_count',
            field=models.IntegerField(default=0),
        ),
    ]
