# Generated by Django 3.0.5 on 2022-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_takeprofitorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='active_order_ids',
            field=models.TextField(default='[]'),
        ),
    ]
