# Generated by Django 3.0.5 on 2022-05-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_trade_active_order_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_precision', models.IntegerField()),
                ('price_precision', models.IntegerField()),
                ('min_price', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
