# Generated by Django 3.0.5 on 2022-05-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_symbolsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolsetting',
            name='symbol',
            field=models.CharField(default='trxusdt', max_length=255),
            preserve_default=False,
        ),
    ]
