# Generated by Django 3.0.5 on 2022-05-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_symbolsetting_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='limit_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='stop_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
