# Generated by Django 3.0.5 on 2022-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220509_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='market',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
