# Generated by Django 3.0.5 on 2022-05-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220509_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='stop_price',
        ),
        migrations.AddField(
            model_name='trade',
            name='stop_percent',
            field=models.FloatField(default=0),
        ),
    ]
