export const icons = {
    clothing: 'shirt-outline',
    electronics: 'phone-portrait-outline',
    books: 'bookmarks-outline',
    cosmetics: 'happy-outline',
    bags: 'briefcase-outline',
    food: 'fast-food-outline',
    household: 'tv-outline',
    furniture: 'today-outline',
    sports: 'football-outline',
    toys: 'cube-outline',
    stationary: 'create-outline',
    pets: 'paw-outline',
    other: 'basket-outline',
}
